### ISSUE TITLE
RNN output shape

### ISSUE THREAD

**Issue by weiwei-ww** [sharathadavanne/multichannel-sed-crnn#1]
Hi,

I got a little confused of the figure in readme. It says the output shape of RNN is 256*64, but should it be 256*32 as the shape of the last RNN layer is 32?

**Comment by sharathadavanne** [comment]
Hi @weiwei-ww thanks for checking this repository.  The output is 256x64 because the RNN used is a bidirectional one. So it returns 256x32 dimension each for forward and backward direction.

**Comment by weiwei-ww** [comment]
Hi, thanks for you quick reply. However, I also noticed that you used the "mul" merge mode for the bidirectional RNN layers. Therefore, I believe that the output dimension should still be 32 instead of 64? Btw, are there any particular reasons of using "mul" instead of "concat" as the merge mode?

**Comment by sharathadavanne** [comment]
@weiwei-ww thanks for pointing it out :) You are right, the code uses 'mul'  mode for bidirectional GRU. So, the figure is definitely misleading.  I will change it at some point. But I must mention that for the DCASE 2017 dataset the performance did not vary much with 'mul' or 'concat'. Since the overall number of weights for the model using 'mul' is less, we chose it over 'concat'.

**Comment by weiwei-ww** [comment]
Thanks for your detailed answer!

**Comment by sharathadavanne** [comment]
@weiwei-ww The figure has now been updated
